# *** SERVER NAME ***
# Displayed in welcome message as 'Welcome to (SERVER_NAME), (player_name)'
SERVER_NAME: "ยงxยงFยงFยง5ยง5ยง5ยง5LยงxยงFยงFยง5ยงAยง5ยง0eยงxยงFยงFยง5ยงFยง4ยงBgยงxยงFยงFยง6ยง4ยง4ยง6eยงxยงFยงFยง6ยง9ยง4ยง1nยงxยงFยงFยง6ยงEยง3ยงCdยงxยงFยงFยง7ยง3ยง3ยง7aยงxยงFยงFยง7ยง8ยง3ยง2rยงxยงFยงFยง7ยงDยง2ยงDy ยงxยงFยงFยง8ยง7ยง2ยง3HยงxยงFยงFยง8ยงCยง1ยงEaยงxยงFยงFยง9ยง1ยง1ยง9rยงxยงFยงFยง9ยง6ยง1ยง4dยงxยงFยงFยง9ยงBยง0ยงFcยงxยงFยงFยงAยง0ยง0ยงAoยงxยงFยงFยงAยง5ยง0ยง5rยงxยงFยงFยงAยงAยง0ยง0eยงr"

# *** GROUP ***
# LuckPerm group settings. Players in the PRE_ONBOARD_GROUP will be onboarded and assigned to POST_ONBOARD_GROUP upon
# accepting the rules and completing the onboard sequence
PRE_ONBOARD_GROUP: "default"
POST_ONBOARD_GROUP: "player"

ONBOARD_GAMEMODE: "survival"
# *** LOCATION ***
# The world and coordinates that the player will be teleported to for onboarding
POS_WORLD: "world"
POS_X: 0
POS_Y: 120
POS_Z: 0
POS_YAW: 0
POS_PITCH: 0

# *** RULES SEQUENCE ***
# Rules and other messages displayed prior to the player being prompted to accept the rules
RULES_SEQUENCE_CONTENT:
  - TITLE: ""
    SUBTITLE: "You are about to join a ยงcpermadeathยงr, semi-anarchy server."
  - TITLE: "ยง6โ"
    SUBTITLE: "Pay attention to the following rules."
  - TITLE: "ยงa\uD83D\uDDE1"
    SUBTITLE: "Griefing, killing and stealing are allowed everywhere and at all times."
  - TITLE: "ยงcโ"
    SUBTITLE: "If you die you are ยงcbanned foreverยงr. You cannot rejoin on another account."
  - TITLE: "ยงc\uD83D\uDEAB"
    SUBTITLE: "Use of hacked clients or mods that give an unfair advantage are not allowed."
  - TITLE: "ยงc\uD83C\uDF70"
    SUBTITLE: "Use of 'pie-ray' or entity counter to find bases or structures is not allowed."
  - TITLE: "ยงa\uD83C\uDF0E"
    SUBTITLE: "Fair play minimaps are allowed, but must have cave mode and entity radar disabled."
  - TITLE: "ยงc\uD83D\uDD27"
    SUBTITLE: "Lag machines and overuse of server resource is not allowed."
  - TITLE: "ยงc๐ชณ"
    SUBTITLE: "Exploitation of bugs is not allowed, with the exception of TNT, rail and gravity-block duping."
  - TITLE: "ยงc\uD83D\uDCAC"
    SUBTITLE: "Slurs, hate speech, extreme harassment and advertising are not allowed."
  - TITLE: ""
    SUBTITLE: "By joining it is assumed that you fully understand and accept these rules."

# How many seconds each rules message should be displayed for, as long as fade in and fade out times
RULES_SEQUENCE_DURATION: 5
RULES_SEQUENCE_FADE_IN: 1
RULES_SEQUENCE_FADE_OUT: 1

# *** PROMPT ACCEPT ***
# The message displayed prompting the player to accept the rules
PROMPT_ACCEPT:
  - TITLE: ""
    SUBTITLE: "Type ยงa/acceptยงr to confirm that you will comply with the rules"
PROMPT_CHAT: "ยง4Type /rules to access the rules at any timeยงr\nยงchttps://wiki.legendaryhc.org/index.php/Rules"

# *** JOIN SEQUENCE ***
# Messages played after the player has accepted the rules and prior to completing onboarding
JOIN_SEQUENCE_CONTENT:
  - TITLE: "ยงcThis is a world without return"
    SUBTITLE: ""
  - TITLE: "ยงcThere are no second chances"
    SUBTITLE: ""
  - TITLE: "ยงcThis is your one life"
    SUBTITLE: ""

# How many seconds each join message should be displayed for, as long as fade in and fade out times
JOIN_SEQUENCE_DURATION: 3
JOIN_SEQUENCE_FADE_IN: 1
JOIN_SEQUENCE_FADE_OUT: 1

# Random spawn range
RANDOM_SPAWN_X1: -3000
RANDOM_SPAWN_Z1: -3000
RANDOM_SPAWN_X2: 3000
RANDOM_SPAWN_Z2: 3000
