# Displayed in welcome message as 'Welcome to (SERVER_NAME), (player_name)'
SERVER_NAME: "Example Server"

# LuckPerm group settings. Players in the PRE_ONBOARD_GROUP will be onboarded and assigned to POST_ONBOARD_GROUP upon
# accepting the rules and completing the onboard sequence
PRE_ONBOARD_GROUP: "default"
POST_ONBOARD_GROUP: "player"

ONBOARD_GAMEMODE: "survival"

# The world and coordinates that the player will be teleported to for onboarding
POS_WORLD: "world"
POS_X: 0
POS_Y: 120
POS_Z: 0
POS_YAW: 0
POS_PITCH: 0

# Rules and other messages displayed prior to the player being prompted to accept the rules
RULES_SEQUENCE_CONTENT:
  - TITLE: "Rules"
    SUBTITLE: "This is the default config"
  - TITLE: ""
    SUBTITLE: "You can change these messages by editing config.yml"
  - TITLE: ""
    SUBTITLE: "§ause §bminecraft §cformatting §dcodes §eto §fadd §9colour"

# How many seconds each rules message should fade in, be displayed for and fade out
RULES_SEQUENCE_FADE_IN: 1
RULES_SEQUENCE_DURATION: 5
RULES_SEQUENCE_FADE_OUT: 1

# The message displayed prompting the player to accept the rules
PROMPT_ACCEPT:
  - TITLE: ""
    SUBTITLE: "The player needs to type §a/accept§r to proceed"
PROMPT_CHAT: "You can also have a message display in chat with a link to a website, discord, etc."

# Messages played after the player has accepted the rules and prior to completing onboarding
JOIN_SEQUENCE_CONTENT:
  - TITLE: "This is a dramatic title sequence"
    SUBTITLE: ""
  - TITLE: ""
    SUBTITLE: "and then the player is randomly teleported"

# How many seconds each join message should fade in, be displayed for and fade out

JOIN_SEQUENCE_DURATION: 3
JOIN_SEQUENCE_FADE_OUT: 1

# Random spawn range
RANDOM_SPAWN_X1: -3000
RANDOM_SPAWN_Z1: -3000
RANDOM_SPAWN_X2: 3000
RANDOM_SPAWN_Z2: 3000
